version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    exclude-paths:
      - "_retired/*"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    exclude-paths:
      - "_retired/*"
